name: Cows Workflow

on:
  push:

jobs:
  run-matrixed:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        prenom: ['marguerite','geraldine','augustine','Séraphine']

    steps:
      # Get the joke
      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1
      # Use the joke output in another step
      - name: Output Dad Joke
        run: echo "BLAGUE=${{ steps.myjoke.outputs.dad-joke }}" >> $GITHUB_ENV

      - name: cow speaking
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: |
            Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}
            Voici une blague: ${{ steps.myjoke.outputs.dad-joke }}