name: Cows Workflow

on:
  schedule:
    - cron: '0 9 * * *'  # Exécuter tous les matins à 9h UTC
    - cron: '0 10 * * *' # Exécuter tous les matins à 10h UTC
    - cron: '*/10 * * * *' # Exécuter toutes les 10 minutes

jobs:
  run-matrixed:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 2
      matrix:
        prenom: ['Marguerite','Geraldine','Augustine','Séraphine']

    steps:
      # Get the joke
      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1

      - name: cow speaking at 9h
        if: github.event_name == 'schedule' && github.event.schedule == '0 9 * * *' && matrix.prenom != 'Séraphine'
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: ${{ env.bonjour }}
        env:
          bonjour: "Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}!"

      - name: cow speaking at 10h
        if: github.event_name == 'schedule' && github.event.schedule == '0 10 * * *' && matrix.prenom == 'Séraphine'
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: ${{ env.bonjour }}
        env:
          bonjour: "Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}!"

      - name: cow speaking every 10mn
        id: Augustine
        if: github.event_name == 'schedule' && github.event.schedule == '*/10 * * * *' && matrix.prenom == 'Augustine'
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: |
            Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}
            Voici une blague: ${{ env.blague }}
        env:
          blague: ${{ steps.myjoke.outputs.dad-joke }}
          

      - name: cow speaking every 5mn after Augustine
        if: github.event_name == 'schedule' && github.event.schedule == '*/10 * * * *' && matrix.prenom == 'Marguerite'
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: ${{ env.blague }}
        env:
          blague: |
            Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}
            "Voici une blague: ${{ steps.Augustine.env.blague }}"
