name: Cows Workflow

on:
  push:

jobs:
  run-matrixed:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        prenom: ['marguerite','geraldine','augustine','Séraphine']

    steps:
      - name: generate random number
        id: random
        run: echo "RANDOM_NUMBER=$(shuf -i 1-6 -n 1)" >> $GITHUB_ENV

      - name: cow speaking
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: |
            Bonjour les DEVOPS, je m'appelle ${{ matrix.prenom }}
            Voici une blague: ${{ env.blague[RANDOM_NUMBER] }}

    env:
      blague: |
        - Quelle est la partie préférée d’un astronaute sur un clavier? L’espace
        - Comment appelle-t-on une chauve-souris avec une perruque ? Une souris
        - Pourquoi les canards sont toujours à l'heure ? Parce qu’ils sont dans l’étang.
        - Que fait un crocodile quand il rencontre une superbe femelle ? Il Lacoste.
        - Pourquoi les pêcheurs ne sont pas gros ? Parce qu’ils surveillent leur ligne.
